### ISSUE TITLE
Suggestion to add Bronze Alloy

### ISSUE THREAD

**Issue by h3oCharles** [ICY105/Mechanization#100]
3 Copper + 1 Tin = 4 Bronze

**Comment by ImCoolYeah105** [comment]
I can add bronze, but the question becomes what is it used for? Not really a point of adding a useless alloy.

As a bit of trivia, Mech 1.0 actually did have bronze but I removed it when I redid the progression system in 2.0

**Comment by h3oCharles** [comment]
https://en.wikipedia.org/wiki/Bronze#Uses

bearings, clips, electrical connectors, springs, cannons, bushings, electric motors, hammers, mallets, wrenches, bronze wool
