### ISSUE TITLE
Cannot burn throw tin via furnace with hoppers

### ISSUE THREAD

**Issue by Shirobachi** [ICY105/Mechanization#120]
I coudn't burn tin via auto furnace, but it worked in single normal furnace.

ss: https://i.imgur.com/9jG4IeK.png
datapacks: https://i.imgur.com/aDC1nJh.png

singleplayer with optifine

**Comment by ICY105** [comment]
So the issue is a hopper can't put raw tin into a furnace? I can't replicate that.

**Comment by Shirobachi** [comment]
Check it out
![Peek 2021-09-03 13-20](https://user-images.githubusercontent.com/16509749/132022304-5094a6fc-6eb9-4f80-a497-b6688f6d95ec.gif)

**Comment by Shirobachi** [comment]
Check it out

https://imgur.com/a/wCiZEra

**Comment by ICY105** [comment]
Try breaking and replacing the furnace? There's no reason inserting items with a hopper would be different then inserting them manually.

**Comment by Shirobachi** [comment]
Yeah it helped, thank you :)
