### ISSUE TITLE
Wrong receipt on book hover for termoelectric generator

### ISSUE THREAD

**Issue by Shirobachi** [ICY105/Mechanization#122]
![Uploading Peek 2021-09-03 13-20.gif…]()

**Comment by Shirobachi** [comment]
![Peek 2021-09-03 13-20](https://user-images.githubusercontent.com/16509749/131997565-0da61b8f-7629-42ee-a305-b80e82b35532.gif)

**Comment by ICY105** [comment]
Fixed in 3.0.2
