### ISSUE TITLE
After brake tree cutter, 'knifes' left

### ISSUE THREAD

**Issue by Shirobachi** [ICY105/Mechanization#123]
https://i.imgur.com/p2bYF3g.png

I tool it by wrench few times, and three times it left. Can I somehow remove it manually / by cheats?

**Comment by ICY105** [comment]
You can remove it with `/kill @e[type=armor_stand,sort=nearest,limit=1]`
I'll try to make sure it gets cleaned up properly...

**Comment by ICY105** [comment]
Fixed in 2.0.3
