### ISSUE TITLE
Recipe of Nether Ingot in the manual appears incorrectly

### ISSUE THREAD

**Issue by MineCommanderCN** [ICY105/Mechanization#126]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
- Mechanization v3.0.3
- DatapackUtilities v2.3.3

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
![image](https://user-images.githubusercontent.com/59791306/133991154-f171f863-08a9-4a78-a526-813834c947f0.png)

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
Minecraft 1.17.1 with Fabric 0.11.6 and a lot of client side mods

4. What if happening vs. what you expect to happen?
In manual:
![image](https://user-images.githubusercontent.com/59791306/133991240-0c99bfe1-6c16-4eac-a39b-23e0dfd50467.png)
Correct picture in wiki:
![image](https://user-images.githubusercontent.com/59791306/133991301-337665f1-169d-4852-bba9-244662116817.png)

**Comment by ICY105** [comment]
fixed in v3.0.4
