### ISSUE TITLE
Liquid Accumulator

### ISSUE THREAD

**Issue by Cordolium** [ICY105/Mechanization#127]
I don't know how liquid accumulator works, I want to pull water out and piped it into the steam generator but I really don't know how it works. I tried using pipes (see attached photo) but still not working.
![image](https://user-images.githubusercontent.com/91123057/134146630-88f48110-36c3-47bc-bf7a-a8cabb941d51.png)

**Comment by ICY105** [comment]
The Liquid Accumulator only picks up liquid on top of it
