### ISSUE TITLE
Mech Storage System and related items

### ISSUE THREAD

**Issue by Cordolium** [ICY105/Mechanization#128]
Hello,

I really appreciate your help last time regarding the liquid accumulator and it is now working. I am quite confused now regarding the MSS Terminal, MSS Storage Drive, and MSS Drive Bay. Can you explain how these actually works? Hope you can help me again, advance thanks! :)

![image](https://user-images.githubusercontent.com/91123057/134373360-5a8cb51a-45a4-455a-853a-b8b68f5756ad.png)

**Comment by ICY105** [comment]
Here's a short video demo: https://youtu.be/-4xqy5cvogY

**Comment by Cordolium** [comment]
Thank you for this video, it was really easy to understand. I already joined to server too. Thanks again, good sir! 😄
