### ISSUE TITLE
Some upgrade effects of rods in Energey Saber calculated/appeared incorrectly

### ISSUE THREAD

**Issue by MineCommanderCN** [ICY105/Mechanization#130]
https://user-images.githubusercontent.com/59791306/134761304-56881f63-cbfd-4225-80a7-1a55b4322ad6.mp4

- The effect of Obsidian Rod shows "Fire Aspect", but it is actually the "Poison".
- The calculation of base stats is counterintuitive - it only uses the best value instead of adding them together.
  - I think this point is acceptable, but it should be pointed out in the wiki & manual.
- Experience gadgets can not be casted in Casting Basin, which is another issue, that means the "Repair" effect can not be gotten in survival mode. Already mentioned in #132.

**Comment by ICY105** [comment]
Obsidian rod will be fixed.

As for the stats, that is WAI. "Base Stats" only uses the highest value, while "Bonus Effects" always apply. I originally wanted and 'everything adds together' system but it was too unbalanced- every setup was brokenly overpowered or completely useless.

**Comment by ICY105** [comment]
fixed in v3.0.4
