### ISSUE TITLE
Nuclear Ascension

### ISSUE THREAD

**Issue by Cordolium** [ICY105/Mechanization#131]
Hello, just wondering, do you have guys a guide on how to use the items in Nuclear Ascension? Or at least do you have a link to a video so I can check it out?

**Comment by MineCommanderCN** [comment]
Please do not ask for help in Issues. Issues are used to report bugs and request new features, but not for comments. Consider looking up in the [Wiki](https://github.com/ICY105/Mechanization/wiki/Fission-Reactor) page or join the Discord server to get help.

**Comment by Cordolium** [comment]
The wiki doesn't have a video link to demonstrate the setup. Plus I tried to ask in discord, yet no one is answering. So I wonder if I can ask for help here.

**Comment by ICY105** [comment]
I answered you in discord. Please remember that time zones exist, I was asleep.

**Comment by Cordolium** [comment]
Ohhhh okay, sorry, I didn't know that you were asleep. Thanks!
