### ISSUE TITLE
Dye Machine

### ISSUE THREAD

**Issue by LTHCTheMaster** [ICY105/Mechanization#137]
Hello, I love this datapack but there is one point which is frustrating me with the Dye Machine, we can color glass and recolor stained glass but why we can't color glass pane and recolor stained glass pane. So my enhancement suggestion is:
  - Can we have the capability to color glass pane and recolor stained glass pane with the dye machine

Thanks for reading and you do a really good work.

**Comment by LTHCTheMaster** [comment]
this datapack
excuse me for the error

**Comment by ICY105** [comment]
Added in 3.0.5
