### ISSUE TITLE
Recipe not working in realms?

### ISSUE THREAD

**Issue by slmint** [ICY105/Mechanization#139]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
- datapackutilities-v2-3-3
- mechanization-datapack-v3-0-4

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
![image](https://user-images.githubusercontent.com/12457032/136078209-6b1f973d-0a4d-4e72-bc97-f36e0bcfaf48.png)

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
realms

4. What if happening vs. what you expect to happen?
machine crafting table Recipe not working in realms ? in Vanilla single player is ok
![image](https://user-images.githubusercontent.com/12457032/136080993-f4de2cd1-525d-4885-80c6-910c1950a6e0.png)

![image](https://user-images.githubusercontent.com/12457032/136080763-8cf8932a-586e-4806-869e-fc6ec8e1a79a.png)

mc 1.17.1

**Comment by ICY105** [comment]
Unfortunately realms deletes all of the recipe predicate files. Not much I can do about it without re-writing the crafting system, sorry.
