### ISSUE TITLE
Raw Copper Block and Raw Gold Block give Molten Iron in Arc Furnace

### ISSUE THREAD

**Issue by Krazy-J** [ICY105/Mechanization#141]
Using latest release (v3.0.4)

Processing `Raw Copper Block` or `Raw Gold Block` gives Molten Iron instead of Moten Copper. It appears a mistake was made when copy-pasting the commands for the different minerals in the function `mechanization:machines/machines/arc_furnace/process_result_vanilla`, specifically in the `loot` commands on lines 32 and 38.

```mcfunction
execute ... run loot replace block -29999999 0 1601 container.0 loot mechanization:base/liquids/vial_of_molten_iron
```

**Comment by ICY105** [comment]
Fixed in 3.0.5
