### ISSUE TITLE
Unable to use the Modular Chestplate with Jetpack upgrade

### ISSUE THREAD

**Issue by Pokemon5252525252** [ICY105/Mechanization#144]
Currently have bukkit (nothing inside), Datapack utils, Mechanization, The Creepers Code.

/reload does not display anything 
![image](https://user-images.githubusercontent.com/68750348/137045560-d97e8511-ef51-401a-b663-8113e07c727b.png)

Running on paperSpigot (Server hosted on MineHut)
No plugins installed

Expectation:
Expected to float up when looking up while jumping once

Reality:
Nothing happens, like literally. It won't let me fly.

**note**
I tested the jetpack alone and it works fine

**Comment by ICY105** [comment]
On spigot, you have to use /minecraft:reload as the reload command is overriden.
Make sure you have a charged portable battery to power the Jetpack.

**Comment by ICY105** [comment]
Ah, this is a bug. The modular chestplate with a jetpack is turned into an elytra, which isn't checked.

**Comment by ICY105** [comment]
Fixed in 3.0.5
