### ISSUE TITLE
Phase Boots Suggestions

### ISSUE THREAD

**Issue by Pokemon5252525252** [ICY105/Mechanization#145]
So the phase boots can walk through walls (e.g sand)

Why not making it walk through glass pane, iron bars, or fences?

**Comment by ICY105** [comment]
I believe it's configured to only walk through solid blocks. Enabling blocks with abnormal hit-boxes may bug it out but I can take a look at it.

**Comment by ICY105** [comment]
After testing this, it really doesn't working well. The boots activate at the wrong times and are difficult to control.
