### ISSUE TITLE
Guidebook not working

### ISSUE THREAD

**Issue by sebastiancat** [ICY105/Mechanization#148]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
mechanization v3.0.5, Datapack Utilitys v2.3.3
2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
it adds a blank line to the chat
3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
single player fabric 1.17.1
4. What if happening vs. what you expect to happen?
when i click one of the apps in the manuel, it closes and says: triggered [mech_manuel] (set value to -2)

**Comment by EpicBirb** [comment]
That is what it is supposed to happen, once you click the apps, turn to the next page to find the information.

**Comment by ICY105** [comment]
Switching apps physically gives you a new book, so it has to close the old one. Opening the new book should have the selected content. This is to prevent issues with a the 100 page cap on spigot, and data overloading chunks.

If it's really not working please respond with more details and I'll reopen the issue.
