### ISSUE TITLE
Manual book is not work

### ISSUE THREAD

**Issue by Tomik151cz** [ICY105/Mechanization#149]
I am playing on 1.18. server,  but manual is not working, and I cant craft everything but manual book i can, where is problem ? 
MechConfig_v3.1.0
Mechanization_Datapack_v3.0.4

DatapackUtilities_v2.3.3

Mech_x32_addon_v2.1.0
and resourcepack on server work

**Comment by CrunchylnMilk** [comment]
Can you be more specific?

You said you can craft the manual but it isn't working; what does that mean? If you are opening the manual and getting a bunch of squares, it means you need to install the resource pack as well. That seems to be the most common manual issue.
