### ISSUE TITLE
Mechanization bugs

### ISSUE THREAD

**Issue by TheMegaComputer** [ICY105/Mechanization#152]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
i have infinite villager restocking, autocraft, wasd machnies, wasd libraries  , more structures ,datapack utilities (2.3.3) and Mechanization 3.0.5 and enchant+
2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
![Screenshot 14](https://user-images.githubusercontent.com/95568205/144743598-91c2c980-f441-4105-b30a-6e8b58e6fbcc.png)

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
fabric 1.17.1 single player
4. What if happening vs. what you expect to happen?
Mechanical manual has no text but has squares ,ore that gives slabs bug machine crafting table shows as barrel and item names item lores and advancemnt names + desc is mech.(name) for items mech.lore.added_by for lore mech.advancement.(name).title for advancement titile and mech.advancement.(name).desc for desc
(note the reload screenshot is everything that it says after the reloa
![2021-12-05_12 36 34](https://user-images.githubusercontent.com/95568205/144743527-661bb899-01d1-4176-918c-b6124f9422f6.png)
![2021-12-05_12 36 42](https://user-images.githubusercontent.com/95568205/144743529-1356ce31-8095-4ef5-93db-2f828d4cf922.png)
![2021-12-05_12 36 50](https://user-images.githubusercontent.com/95568205/144743530-7bea3054-777a-43f3-8f46-6ca11ec2cb74.png)
![2021-12-05_12 37 09](https://user-images.githubusercontent.com/95568205/144743532-1d24047e-7b23-4afc-bdca-a18c613dbb00.png)
![2021-12-05_12 38 06](https://user-images.githubusercontent.com/95568205/144743535-53390201-b1d7-4b49-896d-4859dccf5b22.png)
![2021-12-05_12 38 07](https://user-images.githubusercontent.com/95568205/144743537-e242c223-d47c-4a52-a834-bfcb20cac871.png)
![2021-12-05_12 38 09](https://user
![Screenshot 14](https://user-images.githubusercontent.com/95568205/144743564-47d7774b-777e-4410-aa26-bf734eb654d7.png)
![Screenshot 13](https://user-images.githubusercontent.com/95568205/144743592-7ce09f11-f735-4ef4-8153-cafa1c25e171.png)

d)

**Comment by TheMegaComputer** [comment]
what i think is that a part of the datapack cant load for some reason
and i tested it on other worlds and it was the same result

**Comment by karguli** [comment]
do you have the texturepack for this datapack?

**Comment by CrunchylnMilk** [comment]
Fwiw, it looks like you have the data pack installed, but aren't running the resource pack. The barrel for the crafting table and squares in the manual are pretty strong indicators. For your first step, see if the (correct version) of the resource pack is installed and active.

Bear in mind that if you do have the correct version of the resource pack installed (and active) and are still getting these errors, there can also be resource pack "collisions" for lack of a better word. If you have any other resource packs installed for any of your other datapacks, and they modify the same base blocks/items, Mechanization's resources can be overridden, depending on load order. If this is what's happening, you could:

- change the priority of your resource packs to favor Mechanization, though this may break your other datapacks in turn

- Manually combine the resource packs (as combined ones aren't already available). This is tedious, and beyond the scope of this post, but is the only *real* fix if resource pack collisions are your issue.

**Comment by ICY105** [comment]
Looks like you have:
1. A mod that is breaking everything (try it with fabric and no mods)
2. A conflicting resourcepack

**Comment by krhobbs** [comment]
1. Datapacks Installed: Terralith v2.0.4, Flesh2Leather, Datapack Utilities 3.4.2, Mechanization 3.1.1
2.
![Screen Shot 2022-01-30 at 9 53 05 AM](https://user-images.githubusercontent.com/42527872/151706904-c232f779-6880-4d8b-bf32-06b6eb461b58.png)
3. Vanilla Single Player
4. Grinder with Machine upgrade is not behaving as expected.
    When Grinding gravel it only outputs 1 flint. With the machine upgrade it should output 2 flint.
    The machine is not grinding Ingots or Ancient Debris. I am expecting it to output 2 raw metal for every ingot I put in, but     it is doing nothing with the ingots, same with Ancient Debris.
