### ISSUE TITLE
Energy relays don't work

### ISSUE THREAD

**Issue by Lewyfcb9pro** [ICY105/Mechanization#163]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
     rotten to leather
     Datapack Utilities 2.3.3
     extrarecipes by Mysticat e3351
     Mechanization 304
2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
         "Mysticats Extra Vanilla Recipes Datapackloaded succesfully" everything else works thine though
3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
    Vanilla 1.18/1.18.1
4. What if happening vs. what you expect to happen?
     The Relays don't send Power but recieve it. I expect them to send AND recieve power

**Comment by ICY105** [comment]
Fixed in v4.0.0 prereleases
