### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by Puggington4** [ICY105/Mechanization#165]
Hey man, I know 1.19 has just come out, however I have noticed you haven't been very active.
I just want to know what we may be able to expect.
Thanks 
Puggington

**Comment by ICY105** [comment]
I've brought this up in the discord server but Datapack Utils is being split into separate embedded libraries which means a significant portion of Mech needs to be rewritten. I'm working on it and 1.19 will be out soon-ish (probably ~2 weeks).

**Comment by joeyfigaro** [comment]
Was this completed? The README/documentation still states that datapack utils is a requirement–I'm on 1.19.3 and have mech installed but it's not working. Datapack utils doesn't have compatibility with 1.19.

**Comment by ICY105** [comment]
Installation instructions on the wiki have been updated to reflect that Datapack Utils is no longer a requirement. You do not need to download a seperate library datapack anymore to play Mech.
