### ISSUE TITLE
Can't create a machine frame tier 1

### ISSUE THREAD

**Issue by popos123** [ICY105/Mechanization#173]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
Mechanizations 4.0.5 Prerelease 1, 0g-sugar-africa-mob-dp-v1-6.zip, 1.19.x.data-bubblellaneous-v1.2b, 3D-Editor, cartjump-1-18-v3, incendium-5-1-3, minecraft-dimension-detector-datapack-1.16, -mr-chibis-player-shops-1-19-2, NinjaMoves_demo, overgrown-overworld-e2190, PCraft 1.5, pk-waystones-v-1-0-4, william-wythers-overhauled-overworld-1-19-v1-2
2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
![image](https://user-images.githubusercontent.com/43697578/194612514-a90c5b6f-c8f0-40dc-804d-261434abcb3a.png)
![image](https://user-images.githubusercontent.com/43697578/194629273-c161e561-f1f5-49c3-bb9d-73116775285b.png)

3. What environment are you running the datapack
Nevest paper mc multiplayer
5. What if happening vs. what you expect to happen?
i can't create a machine frame

MC 1.19.2

EDIT:
on 4.0.4 working great

SO IT IS ONLY A BUG OF Mechanizations 4.0.5 Prerelease 1

**Comment by ICY105** [comment]
The prerelease file is prefixed with `_ignore_` because it is broken, but I need the download to ensure some other features work so I can't remove it.
