### ISSUE TITLE
The Nuclear Update and Discord(?)

### ISSUE THREAD

**Issue by Puggington40** [ICY105/Mechanization#181]
Hey man, I'm kinda new and I see its been over four months, I would just like to know if the Nuclear update be released soon and if there is a discord server or somewhere/something that I could use to keep up to date?
All in all, this datapack looks cool, I'd just like to see the nuclear side.
Thanks man
puggington40

**Comment by ICY105** [comment]
Discord: https://discord.gg/6uJ4eJH
Nuclear rework will come out eventually.
