### ISSUE TITLE
Is the double consumption of tin intended?

### ISSUE THREAD

**Issue by TalkingHand** [ICY105/Mechanization#182]
Hello, Thanks for making interesting datapack

1) 4.0.5

2) Tin consumed double when crafting ingots, nuggets, blocks

3) in realm

- I found the code entered twice in some files

'execute if data storage mechanization:temp obj.fluid_item.tag.mechanization.liquid{id:"molten_tin"} run scoreboard players remove @s mechanization.fluid.0 144'

data\mechanization\functions\machines\machines\casting_basin\recipes\output_ingot.mcfunction
data\mechanization\functions\machines\machines\casting_basin\recipes\output_nugget.mcfunction
data\mechanization\functions\machines\machines\casting_basin\recipes\output_block.mcfunction

Is this intended?

**Comment by ICY105** [comment]
Fixed in v4.1.0
