### ISSUE TITLE
File bug and wiki bug

### ISSUE THREAD

**Issue by nekonomura** [ICY105/Mechanization#183]
File bug

in [4.0.5](https://github.com/ICY105/Mechanization/releases/tag/4.0.5)

Filename  and file are ok?

"[mechanization_v2.0.5.zip](https://github.com/ICY105/Mechanization/releases/download/4.0.5/mechanization_v2.0.5.zip)"
---------------------------------------------------------------------------------------------------------------------------------------
Wiki bug

Machine Frames recipe may be old.

**Comment by ICY105** [comment]
Fixed
