### ISSUE TITLE
carrot in bio reactor crashing server

### ISSUE THREAD

**Issue by prboba** [ICY105/Mechanization#184]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).

DatapackUtilities_v2.3.3
mechanization-v2-0-5

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).

[latest.log](https://github.com/ICY105/Mechanization/files/10472498/latest.log)
crush after player load chunk with generator at line 612

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.

purpur (spigot fork)

4. What if happening vs. what you expect to happen?

carrot in bio reactor crashing server, i think it shouldn't

**Comment by ICY105** [comment]
Mech no longer requires DatapackUtils. Remove it and see if you get the same problem.

**Comment by prboba** [comment]
> Mech no longer requires DatapackUtils. Remove it and see if you get the same problem.

Doesn't help

**Comment by ICY105** [comment]
Should be fixed in v4.1.0, but spigot does stupid things sometimes.
