### ISSUE TITLE
Grinder does not accept mangrove logs

### ISSUE THREAD

**Issue by haleyjd** [ICY105/Mechanization#186]
Examining the source code shows that the grinder doesn't include a case for mangrove logs despite accepting all the other vanilla logs. I presume this was just forgotten for the 1.19 upgrade. (cf. https://github.com/ICY105/Mechanization/blob/42050ba1f55d95c519dca97387393b6edc603f02/data/mechanization/functions/machines/machines/grinder/input.mcfunction#L59 )

**Comment by ICY105** [comment]
Fixed in v4.1.0
