### ISSUE TITLE
Unable to make alloys in the alloy furnace after adding normal machine upgrade

### ISSUE THREAD

**Issue by Dark-Carnage** [ICY105/Mechanization#190]
I can't make any alloys in the alloy furnace. It just shows it smelting indefinitely. I just added the normal machine upgrade to it.

**Comment by ICY105** [comment]
Fixed in v4.1.1

**Comment by Dark-Carnage** [comment]
Has v4.1.1 released yet?

**Comment by ICY105** [comment]
yes
