### ISSUE TITLE
Drill with mining area upgrade bug

### ISSUE THREAD

**Issue by magmamir** [ICY105/Mechanization#191]
In both: 4.0.5 and 4.1.0 versions, when drill's mining area function breaks chests (or any other block that have an inventory, except shulker boxes) that block drops only itself, but not items that stored in it. So, if you mine some block with the drill with this upgrade, and there is a chest next to the minable block, you lose all items in it. To fix this, you should probably use _setblock air destroy_ instead of _loot_ on block entities, that could store items (like chests or jukeboxes). I'm not sure about custom blocks from all datapacks but breaking of smitched crafing table and simpleenergy's blocks work pretty fine.

Also, i wanna say that tinker table, with item in it, lags and takes TPS/ms.avg pretty noticeably, and just too much for custom block with gui (from this dp or not). I don't know how to fix it, just wanted to inform you.

**Comment by ICY105** [comment]
Fixed in v4.1.1
