### ISSUE TITLE
Version Error Appears in Chat 

### ISSUE THREAD

**Issue by Cuplex17** [ICY105/Mechanization#193]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
- Mechanisation 4.1.1
- Mechanisation Config
- 
2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
Error: Incorrect version

4. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
Forge Singleplayer Minecraft 1.20

6. What if happening vs. what you expect to happen?
Error regarding incorrect version displays in chat despite datapack slated for 1.20 and 1.20.1

**Comment by ICY105** [comment]
Fixed in 4.1.2
