### ISSUE TITLE
Redstone gear/plate/rod recipe

### ISSUE THREAD

**Issue by Reflex0283** [ICY105/Mechanization#195]
1. Stellarity, Incendium, Creeper's Code, and Mechanization (Mechanization is the one with the problem I think)

2. don't have access to the server

3. Paper server, vanilla except for datapacks

4. I can't find the recipe for redstone gears in the mechanical menu

**Comment by ICY105** [comment]
Gemstone Gears (redstone, diamond, lapis, etc) cannot be crafted and are made using the Casting Basin.
