### ISSUE TITLE
Ores won't smelt

### ISSUE THREAD

**Issue by TheCelestialMan** [ICY105/Mechanization#196]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).

arboria-saplings-v1-1.zip
  |   | better-genetics-v1-9-1
  |   | Incendium_1.20_5.3.0
  |   | MechanizationConfig_v4.1.4
  |   | MechanizationDatapack_v4.1.4a
  |   | Nullscape_1.20_v1.2.1
  |   | rotten-flesh-to-leather_1.20.1
  |   | Structory_1.20_1.3.2
  |   | Terralith_1.20_v2.4.0.zip 
  |   | treesneakgrow-v2-0.zip 
  |   | §7Chains §8§l[DATAPACK].zip

2. Run /reload. Copy/paste or post a screenshot of what appears in chat (should say [Loaded <datapack> <version>]).
Nothing appears in chat

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
Paper Server 1.20.1
4. What if happening vs. what you expect to happen?
My Tin and Titanium aren't smelting. I put them in the furnace and blast furnace and nothing happens. I'm not too sure how else to get tin ingots since the book doesn't talk about early game ingots and how to get them. I figured it would be smelting like normal but nothing happens.

**Comment by ICY105** [comment]
Try breaking & replacing the furnace, they may not be marked correctly. If that doesn't help try it without paper.

**Comment by TheCelestialMan** [comment]
> Try breaking & replacing the furnace, they may not be marked correctly. If that doesn't help try it without paper.

Replacing it worked, thanks!
