### ISSUE TITLE
Quarry needed to be restarted whenever it is unloaded.

### ISSUE THREAD

**Issue by RedCocoon** [ICY105/Mechanization#197]
1. What datapack(s) do you have installed (including ones made by me- include version if possible).
Battledoors
Bugnet
Combat+
Explorer's Advent
Chairs (Gm4)
Ziprails (Gm4)
Grappling Hook
Manic
Mechanization
The Creeper's Code 
Gravestones
Crawly
GM4 Shapeles Portals
GM4 Vertical Rails

2. Ensure the datapack is loaded  with `/datapack list`
Yes

3. What environment are you running the datapack? (Vanilla single player, Vanilla multiplayer, Forge, fabric, spigot, bukkit, paper, optifine, realms, etc). Please specify exact Minecraft version as well.
Fabric (I assume? I'm playing on a server) 1.20.1

4. What if happening vs. what you expect to happen?
Quarry seems to forget its progress when it is unloaded and reloaded, for some reason. Because of this, I had to re-wrench the boundary and restart the quarry all over again. The quarry should remember its boundary and resume operation when it is reloaded.

**Comment by ICY105** [comment]
Fixed in 4.2.0
