### ISSUE TITLE
Nether/Ender Alloy treated as Tier II Material

### ISSUE THREAD

**Issue by luciossjaen** [ICY105/Mechanization#198]
Alloy Furnace with Ender Upgrade (10% for Tier II alloys to be duplicated) affects Ender Alloy and Nether Alloy in 1.20.1.

Randomly happened when swapping machines around and when thinking about it, they were never affected by Nether Upgrade in a different Alloy Furnace so far.

My assumption was that Nether / Ender Alloy would be Tier III (or not tiered at all), but thought to put it in here since at least in the Manual they are not part of the Tier II section.

**Comment by ICY105** [comment]
Fixed in 4.2.0
