### ISSUE TITLE
Issues with specific items.

### ISSUE THREAD

**Issue by Dokkan-Phoenix** [ICY105/Mechanization#30]
I run a private server, with a few of my friends. We LOVE this data pack. However we are running into a gamebreaking error, One, it seems like we cannot craft a quarry, AT ALL, same goes with Machine Upgrades, and two, crystal composite kicks us from the server if the alloy furnace that has it is opened. If you break it with a pickaxe, instead of a wrench, you will be nonstop kicked from the game until you delete the playerdata of the player associated. This is the error in console when someone tries to see the crystal composite: User f28maniac7 has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: 
12.08 10:28:45 [Server] ERROR java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]:

**Comment by Darkspyro911** [comment]
sorry to hear about that since imCoolYha updated how the park works
he/she has to start like new for the items, Please be patient as only
1 person is working on this pack

On 8/12/18, CodyDoesThings <notifications@github.com> wrote:
> I run a private server, with a few of my friends. We LOVE this data pack.
> However we are running into a gamebreaking error, One, it seems like we
> cannot craft a quarry, AT ALL, same goes with Machine Upgrades, and two,
> crystal composite kicks us from the server if the alloy furnace that has it
> is opened. If you break it with a pickaxe, instead of a wrench, you will be
> nonstop kicked from the game until you delete the playerdata of the player
> associated. This is the error in console when someone tries to see the
> crystal composite: User f28maniac7 has disconnected, reason: Internal
> Exception: io.netty.handler.codec.EncoderException:
> java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]:
> 12.08 10:28:45 [Server] ERROR java.lang.IllegalArgumentException: Invalid
> key. Must be [a-z0-9/._-]:
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/30


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by CodyDoesThings** [comment]
Thank you, this may just be a serverside issue, as it works on single player, im looking through the functions atm to see if i can resolve this issue

**Comment by CodyDoesThings** [comment]
So far its firing blanks, i cant seem to locate an issue. and its just the crystal composite, everything else works

**Comment by ImCoolYeah105** [comment]
The pickaxe/axe were accidentally swapped in the recipe, This will be fixed next update (you can reverse them to craft it for now). I'll check in on the machine upgrade recipe (the crafting system was recently rewritten, so there have been a bunch of bugs with it).

I'll check in on the crystal composite. Sounds like a stray character got into the item name.
