### ISSUE TITLE
New Item Suggestions

### ISSUE THREAD

**Issue by Dreamer81382** [ICY105/Mechanization#36]
If you're looking for suggestions on some new items to make, here are some for your consideration. I've been thoroughly enjoying Mechanization thus far and I love playing with it, you've done an excellent job!

1.) Tracking Beacon - This would be a two-part item; the Tracker itself and the Beacon (or Beacons). The Beacon would be a small item that could easily be placed onto and removed from nearly any block. The Tracker could then be held in your off-hand and would then act like a Compass (with the Beacon essentially creating a temporary "SetWorldSpawn" effect) and help lead you to the location of the Beacon. This can help if you're caving or exploring far from your Spawn Point/Bed and you wish to find your way back to your Nether Portal (or find your way back to a Cave system after leaving). The Tracker could then be upgraded to track multiple beacons at once (which you could cycle through by Left-Clicking).

2.) Mob Caller - This is an item that would effectively "call" all mobs in the area to it, allowing you to then kill and farm them with the Mob Grinder. The Mob Grinder is great for farming drops, and you could theoretically use the Spawner Mover and Creative Mode to have whatever kind of Spawner you want. But when playing survival mode, you could use the Mob Caller instead to draw all the mobs in the area to a single location, rather than hunting for them (this would be especially useful in the Nether and you want to farm Wither Skulls). You could also switch the Mob Caller from "Hostile" to "Passive" and it would instead call all Passive Mobs (like Sheep, Cows, etc) to it; again, eliminating the need to hunt them down and lead them back to a single location one by one. An Upgrade could either attract the hostile mobs, allow for functionality in other dimensions (Nether, End, etc), or simply extend the range.

3.) Biome Finder / Map Maker - This would be immensely useful in Vanilla Minecraft if you were able to find a way to implement it. It is a Machine that would allow you to plug in/type in/search for the name of any Biome (like a Mooshroom Island), and the Machine would produce a Map to it (much in the same way that Cartographers produce Maps to Woodland Mansions and Ocean Monuments). Alternatively, You could simply place the Machine down somewhere and it would create a fully-fleshed out (and extended) map of the surrounding area (thus, eliminating the need to fly around and fill out the map yourself), you could then pick it up, place it in a new area, and get a new map.  The /locate command is great for finding structures, but I wished it worked for individual Biomes (sometimes, you really need Podzol or Mycelium and don't want to just Creative them in). An Upgraded Version could allow for use in (and mapping of) the Nether and End Dimensions.  

4.) Portable Battery Upgrade - Upgrade the Portable Battery to hold more power (or make them stackable). I usually end up having to take 5 or 6 with me at a time because I end up using so much from all of my armor and item pieces (plus using the guns). 

I hope you find these ideas useful. Thank You again for a great product. Keep up the good work :)

**Comment by ImCoolYeah105** [comment]
1. I think this would be possible, though not easy. I'll look into it.

2. Messing with mobs outside of a small radius is very tricky. Usually it involves UUID manipulation, which is hard, prone to bugging out, and usually has the restriction of only 1 machine being in the world at a time, so not very practical. However, you could use a villager to at least attract zombies, and an endermite for endermen.

3. Currently it is possible to test for which biome a player is currently in, but there is no other way to test for biomes. Additionally, even if you could test for a biome, the chunks would have to be loaded, making this somewhat unpractical.

4. Never really felt a need for a bigger battery, though there are some particularity power hungry upgrades I tended to not use in my play-throughs. An upgraded battery would be possible to add, so I'll look into it.

**Comment by Darkspyro911** [comment]
here is a biome specific generator
https://www.tyruswoo.com/minecraft-game-changer

On 9/3/18, ImCoolYeah105 <notifications@github.com> wrote:
> 1. I think this would be possible, though not easy. I'll look into it.
>
> 2. Messing with mobs outside of a small radius is very tricky. Usually it
> involves UUID manipulation, which is hard, prone to bugging out, and usually
> has the restriction of only 1 machine being in the world at a time, so not
> very practical. However, you could use a villager to at least attract
> zombies, and an endermite for endermen.
>
> 3. Currently it is possible to test for which biome a player is currently
> in, but there is no other way to test for biomes. Additionally, even if you
> could test for a biome, the chunks would have to be loaded, making this
> somewhat unpractical.
>
> 4. Never really felt a need for a bigger battery, though there are some
> particularity power hungry upgrades I tended to not use in my play-throughs.
> An upgraded battery would be possible to add, so I'll look into it.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/36#issuecomment-418192138


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by Dreamer81382** [comment]
What about an Item De-constructor?

A machine that would take a crafted item and break it apart into its base components. For example, taking all of those tripwire hooks that you get from your Auto-Fisher and turning them back into Planks, Sticks, and Iron Ingots.  Essentially reversing the crafting table recipes.

**Comment by Darkspyro911** [comment]
there is a item that does that its called the decompressor

On 9/5/18, Dreamer81382 <notifications@github.com> wrote:
> What about an Item De-constructor?
>
> A machine that would take a crafted item and break it apart into its base
> components. For example, taking all of those tripwire hooks that you get
> from your Auto-Fisher and turning them back into Planks, Sticks, and Iron
> Ingots.  Essentially reversing the crafting table recipes.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ImCoolYeah105/Mechanization/issues/36#issuecomment-418611707


-- 
Marc-Andre Maurice
mauricemarcandre@gmail.com

**Comment by ImCoolYeah105** [comment]
Un-crafters are almost always brokenly overpowered. There is very rarely a way to balance them, so I don't think I will add one. For the moment, you can get the machine frame back by breaking the block normally without a wrench (though you loss all the extra ingredients of course).
