### ISSUE TITLE
Suggestion to use OptiFine CIT for some items

### ISSUE THREAD

**Issue by h3oCharles** [ICY105/Mechanization#99]
I've looked around the wiki and some items after crafting appear as vanilla items. Since you're already using a resource pack, why not use OptiFine's CIT to make models of these new items?

**Comment by ImCoolYeah105** [comment]
I believe all previous instances of items looking like vanilla items have been replaced, though the wiki images may not be up to date.
In general I try to avoid using Optifine as it's not always available and/or people don't, won't, or can't use Optifine. I would maybe consider some Optifine enhancements if it didn't affect users without Optifine.

**Comment by simon511000** [comment]
yes it is a limitation of minecraft and we can not do anything about it
